version: '3.8'
services:
  web:
    container_name: gunicorn_django
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    volumes:
      - static_volume:/usr/src/app/software/static
      - media_volume:/usr/src/app/software/media
    depends_on:
      - db
    networks:
      prod_network:
        ipv4_address: 172.18.1.2
  db:
    container_name: postgres
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      prod_network:
        ipv4_address: 172.18.1.3
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/usr/src/app/software/static
      - media_volume:/usr/src/app/software/media
    depends_on:
      - web
    networks:
      prod_network:
        ipv4_address: 172.18.1.4
networks:
  prod_network:
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/24
volumes:
  postgres_volume:
  static_volume:
  media_volume:
