# Generated by Django 3.2.20 on 2023-10-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='sono',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='tag',
            field=models.CharField(max_length=3),
        ),
    ]
