# Generated by Django 3.2.20 on 2023-10-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_alter_inspection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='sono',
            field=models.CharField(max_length=8),
        ),
    ]
